# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_api import ApiApi


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApi()

    def tearDown(self) -> None:
        pass

    def test_api_schema_retrieve(self) -> None:
        """Test case for api_schema_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
