# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_create(self) -> None:
        """Test case for auth_create

        """
        pass

    def test_session_destroy(self) -> None:
        """Test case for session_destroy

        """
        pass

    def test_session_retrieve(self) -> None:
        """Test case for session_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
