# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.null_enum import NullEnum

class TestNullEnum(unittest.TestCase):
    """NullEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNullEnum(self):
        """Test NullEnum"""
        # inst = NullEnum()

if __name__ == '__main__':
    unittest.main()
