# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.session_response import SessionResponse

class TestSessionResponse(unittest.TestCase):
    """SessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionResponse:
        """Test SessionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionResponse`
        """
        model = SessionResponse()
        if include_optional:
            return SessionResponse(
                access_token = '',
                token_type = ''
            )
        else:
            return SessionResponse(
                access_token = '',
                token_type = '',
        )
        """

    def testSessionResponse(self):
        """Test SessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
