# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.proofs_api import ProofsApi


class TestProofsApi(unittest.TestCase):
    """ProofsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProofsApi()

    def tearDown(self) -> None:
        pass

    def test_proofs_destroy(self) -> None:
        """Test case for proofs_destroy

        """
        pass

    def test_proofs_list(self) -> None:
        """Test case for proofs_list

        """
        pass

    def test_proofs_partial_update(self) -> None:
        """Test case for proofs_partial_update

        """
        pass

    def test_proofs_retrieve(self) -> None:
        """Test case for proofs_retrieve

        """
        pass

    def test_proofs_upload_create(self) -> None:
        """Test case for proofs_upload_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
