# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.blank_enum import BlankEnum

class TestBlankEnum(unittest.TestCase):
    """BlankEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlankEnum(self):
        """Test BlankEnum"""
        # inst = BlankEnum()

if __name__ == '__main__':
    unittest.main()
