# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.prices_api import PricesApi


class TestPricesApi(unittest.TestCase):
    """PricesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricesApi()

    def tearDown(self) -> None:
        pass

    def test_prices_create(self) -> None:
        """Test case for prices_create

        """
        pass

    def test_prices_destroy(self) -> None:
        """Test case for prices_destroy

        """
        pass

    def test_prices_list(self) -> None:
        """Test case for prices_list

        """
        pass

    def test_prices_partial_update(self) -> None:
        """Test case for prices_partial_update

        """
        pass

    def test_prices_retrieve(self) -> None:
        """Test case for prices_retrieve

        """
        pass

    def test_prices_stats_retrieve(self) -> None:
        """Test case for prices_stats_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
