# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patched_proof_update import PatchedProofUpdate

class TestPatchedProofUpdate(unittest.TestCase):
    """PatchedProofUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedProofUpdate:
        """Test PatchedProofUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedProofUpdate`
        """
        model = PatchedProofUpdate()
        if include_optional:
            return PatchedProofUpdate(
                type = 'PRICE_TAG',
                currency = None,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return PatchedProofUpdate(
        )
        """

    def testPatchedProofUpdate(self):
        """Test PatchedProofUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
