# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paginated_user_list import PaginatedUserList

class TestPaginatedUserList(unittest.TestCase):
    """PaginatedUserList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedUserList:
        """Test PaginatedUserList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedUserList`
        """
        model = PaginatedUserList()
        if include_optional:
            return PaginatedUserList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    openapi_client.models.user.User(
                        user_id = '', 
                        price_count = 0, 
                        location_count = 0, 
                        product_count = 0, 
                        proof_count = 0, )
                    ]
            )
        else:
            return PaginatedUserList(
                count = 123,
                results = [
                    openapi_client.models.user.User(
                        user_id = '', 
                        price_count = 0, 
                        location_count = 0, 
                        product_count = 0, 
                        proof_count = 0, )
                    ],
        )
        """

    def testPaginatedUserList(self):
        """Test PaginatedUserList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
