# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.total_stats import TotalStats

class TestTotalStats(unittest.TestCase):
    """TotalStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TotalStats:
        """Test TotalStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TotalStats`
        """
        model = TotalStats()
        if include_optional:
            return TotalStats(
                price_count = 0,
                price_barcode_count = 0,
                price_category_count = 0,
                product_count = 0,
                product_with_price_count = 0,
                location_count = 0,
                location_with_price_count = 0,
                proof_count = 0,
                proof_with_price_count = 0,
                user_count = 0,
                user_with_price_count = 0,
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TotalStats(
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTotalStats(self):
        """Test TotalStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
