# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.price_create import PriceCreate

class TestPriceCreate(unittest.TestCase):
    """PriceCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceCreate:
        """Test PriceCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceCreate`
        """
        model = PriceCreate()
        if include_optional:
            return PriceCreate(
                price = 0,
                price_is_discounted = True,
                price_without_discount = 0,
                price_per = None,
                currency = None,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                product_code = '',
                product_name = '',
                category_tag = '',
                labels_tags = None,
                origins_tags = None,
                location_osm_id = 0,
                location_osm_type = None,
                proof_id = 56
            )
        else:
            return PriceCreate(
                proof_id = 56,
        )
        """

    def testPriceCreate(self):
        """Test PriceCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
