# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.session_full import SessionFull

class TestSessionFull(unittest.TestCase):
    """SessionFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionFull:
        """Test SessionFull
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionFull`
        """
        model = SessionFull()
        if include_optional:
            return SessionFull(
                user_id = '',
                token = '',
                created = '',
                last_used = ''
            )
        else:
            return SessionFull(
                user_id = '',
                token = '',
                created = '',
                last_used = '',
        )
        """

    def testSessionFull(self):
        """Test SessionFull"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
