# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.locations_api import LocationsApi


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LocationsApi()

    def tearDown(self) -> None:
        pass

    def test_locations_create(self) -> None:
        """Test case for locations_create

        """
        pass

    def test_locations_list(self) -> None:
        """Test case for locations_list

        """
        pass

    def test_locations_osm_retrieve(self) -> None:
        """Test case for locations_osm_retrieve

        """
        pass

    def test_locations_retrieve(self) -> None:
        """Test case for locations_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
