# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.location_osm_type_enum import LocationOsmTypeEnum

class TestLocationOsmTypeEnum(unittest.TestCase):
    """LocationOsmTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationOsmTypeEnum(self):
        """Test LocationOsmTypeEnum"""
        # inst = LocationOsmTypeEnum()

if __name__ == '__main__':
    unittest.main()
