# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.products_api import ProductsApi


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()

    def tearDown(self) -> None:
        pass

    def test_products_code_retrieve(self) -> None:
        """Test case for products_code_retrieve

        """
        pass

    def test_products_list(self) -> None:
        """Test case for products_list

        """
        pass

    def test_products_retrieve(self) -> None:
        """Test case for products_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
