# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TotalStats(BaseModel):
    """
    TotalStats
    """ # noqa: E501
    price_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    price_barcode_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    price_category_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    product_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    product_with_price_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    location_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    location_with_price_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    proof_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    proof_with_price_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    user_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    user_with_price_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    updated: datetime
    __properties: ClassVar[List[str]] = ["price_count", "price_barcode_count", "price_category_count", "product_count", "product_with_price_count", "location_count", "location_with_price_count", "proof_count", "proof_with_price_count", "user_count", "user_with_price_count", "updated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TotalStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "updated",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TotalStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "price_count": obj.get("price_count"),
            "price_barcode_count": obj.get("price_barcode_count"),
            "price_category_count": obj.get("price_category_count"),
            "product_count": obj.get("product_count"),
            "product_with_price_count": obj.get("product_with_price_count"),
            "location_count": obj.get("location_count"),
            "location_with_price_count": obj.get("location_with_price_count"),
            "proof_count": obj.get("proof_count"),
            "proof_with_price_count": obj.get("proof_with_price_count"),
            "user_count": obj.get("user_count"),
            "user_with_price_count": obj.get("user_with_price_count"),
            "updated": obj.get("updated")
        })
        return _obj


