# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    User
    """ # noqa: E501
    user_id: StrictStr
    price_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    location_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    product_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    proof_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["user_id", "price_count", "location_count", "product_count", "proof_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if price_count (nullable) is None
        # and model_fields_set contains the field
        if self.price_count is None and "price_count" in self.model_fields_set:
            _dict['price_count'] = None

        # set to None if location_count (nullable) is None
        # and model_fields_set contains the field
        if self.location_count is None and "location_count" in self.model_fields_set:
            _dict['location_count'] = None

        # set to None if product_count (nullable) is None
        # and model_fields_set contains the field
        if self.product_count is None and "product_count" in self.model_fields_set:
            _dict['product_count'] = None

        # set to None if proof_count (nullable) is None
        # and model_fields_set contains the field
        if self.proof_count is None and "proof_count" in self.model_fields_set:
            _dict['proof_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "price_count": obj.get("price_count"),
            "location_count": obj.get("location_count"),
            "product_count": obj.get("product_count"),
            "proof_count": obj.get("proof_count")
        })
        return _obj


