# coding: utf-8

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.paginated_product_full_list import PaginatedProductFullList
from openapi_client.models.product_full import ProductFull

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class ProductsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def products_code_retrieve(
        self,
        code: Annotated[str, Field(strict=True)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ProductFull:
        """products_code_retrieve


        :param code: (required)
        :type code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_code_retrieve_serialize(
            code=code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProductFull",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def products_code_retrieve_with_http_info(
        self,
        code: Annotated[str, Field(strict=True)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ProductFull]:
        """products_code_retrieve


        :param code: (required)
        :type code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_code_retrieve_serialize(
            code=code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProductFull",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def products_code_retrieve_without_preload_content(
        self,
        code: Annotated[str, Field(strict=True)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """products_code_retrieve


        :param code: (required)
        :type code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_code_retrieve_serialize(
            code=code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProductFull",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _products_code_retrieve_serialize(
        self,
        code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if code is not None:
            _path_params['code'] = code
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth', 
            'cookieAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/products/code/{code}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def products_list(
        self,
        brands__like: Optional[StrictStr] = None,
        brands_tags__contains: Optional[StrictStr] = None,
        categories_tags__contains: Optional[StrictStr] = None,
        code: Optional[StrictStr] = None,
        ecoscore_grade: Optional[StrictStr] = None,
        labels_tags__contains: Optional[StrictStr] = None,
        nova_group: Optional[StrictInt] = None,
        nutriscore_grade: Optional[StrictStr] = None,
        order_by: Annotated[Optional[StrictStr], Field(description="Which field to use when ordering the results.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="A page number within the paginated result set.")] = None,
        price_count: Optional[StrictInt] = None,
        price_count__gte: Optional[StrictInt] = None,
        price_count__lte: Optional[StrictInt] = None,
        product_name__like: Optional[StrictStr] = None,
        size: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        source: Annotated[Optional[StrictStr], Field(description="* `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro")] = None,
        unique_scans_n__gte: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaginatedProductFullList:
        """products_list


        :param brands__like:
        :type brands__like: str
        :param brands_tags__contains:
        :type brands_tags__contains: str
        :param categories_tags__contains:
        :type categories_tags__contains: str
        :param code:
        :type code: str
        :param ecoscore_grade:
        :type ecoscore_grade: str
        :param labels_tags__contains:
        :type labels_tags__contains: str
        :param nova_group:
        :type nova_group: int
        :param nutriscore_grade:
        :type nutriscore_grade: str
        :param order_by: Which field to use when ordering the results.
        :type order_by: str
        :param page: A page number within the paginated result set.
        :type page: int
        :param price_count:
        :type price_count: int
        :param price_count__gte:
        :type price_count__gte: int
        :param price_count__lte:
        :type price_count__lte: int
        :param product_name__like:
        :type product_name__like: str
        :param size: Number of results to return per page.
        :type size: int
        :param source: * `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro
        :type source: str
        :param unique_scans_n__gte:
        :type unique_scans_n__gte: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_list_serialize(
            brands__like=brands__like,
            brands_tags__contains=brands_tags__contains,
            categories_tags__contains=categories_tags__contains,
            code=code,
            ecoscore_grade=ecoscore_grade,
            labels_tags__contains=labels_tags__contains,
            nova_group=nova_group,
            nutriscore_grade=nutriscore_grade,
            order_by=order_by,
            page=page,
            price_count=price_count,
            price_count__gte=price_count__gte,
            price_count__lte=price_count__lte,
            product_name__like=product_name__like,
            size=size,
            source=source,
            unique_scans_n__gte=unique_scans_n__gte,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedProductFullList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def products_list_with_http_info(
        self,
        brands__like: Optional[StrictStr] = None,
        brands_tags__contains: Optional[StrictStr] = None,
        categories_tags__contains: Optional[StrictStr] = None,
        code: Optional[StrictStr] = None,
        ecoscore_grade: Optional[StrictStr] = None,
        labels_tags__contains: Optional[StrictStr] = None,
        nova_group: Optional[StrictInt] = None,
        nutriscore_grade: Optional[StrictStr] = None,
        order_by: Annotated[Optional[StrictStr], Field(description="Which field to use when ordering the results.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="A page number within the paginated result set.")] = None,
        price_count: Optional[StrictInt] = None,
        price_count__gte: Optional[StrictInt] = None,
        price_count__lte: Optional[StrictInt] = None,
        product_name__like: Optional[StrictStr] = None,
        size: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        source: Annotated[Optional[StrictStr], Field(description="* `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro")] = None,
        unique_scans_n__gte: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaginatedProductFullList]:
        """products_list


        :param brands__like:
        :type brands__like: str
        :param brands_tags__contains:
        :type brands_tags__contains: str
        :param categories_tags__contains:
        :type categories_tags__contains: str
        :param code:
        :type code: str
        :param ecoscore_grade:
        :type ecoscore_grade: str
        :param labels_tags__contains:
        :type labels_tags__contains: str
        :param nova_group:
        :type nova_group: int
        :param nutriscore_grade:
        :type nutriscore_grade: str
        :param order_by: Which field to use when ordering the results.
        :type order_by: str
        :param page: A page number within the paginated result set.
        :type page: int
        :param price_count:
        :type price_count: int
        :param price_count__gte:
        :type price_count__gte: int
        :param price_count__lte:
        :type price_count__lte: int
        :param product_name__like:
        :type product_name__like: str
        :param size: Number of results to return per page.
        :type size: int
        :param source: * `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro
        :type source: str
        :param unique_scans_n__gte:
        :type unique_scans_n__gte: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_list_serialize(
            brands__like=brands__like,
            brands_tags__contains=brands_tags__contains,
            categories_tags__contains=categories_tags__contains,
            code=code,
            ecoscore_grade=ecoscore_grade,
            labels_tags__contains=labels_tags__contains,
            nova_group=nova_group,
            nutriscore_grade=nutriscore_grade,
            order_by=order_by,
            page=page,
            price_count=price_count,
            price_count__gte=price_count__gte,
            price_count__lte=price_count__lte,
            product_name__like=product_name__like,
            size=size,
            source=source,
            unique_scans_n__gte=unique_scans_n__gte,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedProductFullList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def products_list_without_preload_content(
        self,
        brands__like: Optional[StrictStr] = None,
        brands_tags__contains: Optional[StrictStr] = None,
        categories_tags__contains: Optional[StrictStr] = None,
        code: Optional[StrictStr] = None,
        ecoscore_grade: Optional[StrictStr] = None,
        labels_tags__contains: Optional[StrictStr] = None,
        nova_group: Optional[StrictInt] = None,
        nutriscore_grade: Optional[StrictStr] = None,
        order_by: Annotated[Optional[StrictStr], Field(description="Which field to use when ordering the results.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="A page number within the paginated result set.")] = None,
        price_count: Optional[StrictInt] = None,
        price_count__gte: Optional[StrictInt] = None,
        price_count__lte: Optional[StrictInt] = None,
        product_name__like: Optional[StrictStr] = None,
        size: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        source: Annotated[Optional[StrictStr], Field(description="* `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro")] = None,
        unique_scans_n__gte: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """products_list


        :param brands__like:
        :type brands__like: str
        :param brands_tags__contains:
        :type brands_tags__contains: str
        :param categories_tags__contains:
        :type categories_tags__contains: str
        :param code:
        :type code: str
        :param ecoscore_grade:
        :type ecoscore_grade: str
        :param labels_tags__contains:
        :type labels_tags__contains: str
        :param nova_group:
        :type nova_group: int
        :param nutriscore_grade:
        :type nutriscore_grade: str
        :param order_by: Which field to use when ordering the results.
        :type order_by: str
        :param page: A page number within the paginated result set.
        :type page: int
        :param price_count:
        :type price_count: int
        :param price_count__gte:
        :type price_count__gte: int
        :param price_count__lte:
        :type price_count__lte: int
        :param product_name__like:
        :type product_name__like: str
        :param size: Number of results to return per page.
        :type size: int
        :param source: * `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro
        :type source: str
        :param unique_scans_n__gte:
        :type unique_scans_n__gte: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_list_serialize(
            brands__like=brands__like,
            brands_tags__contains=brands_tags__contains,
            categories_tags__contains=categories_tags__contains,
            code=code,
            ecoscore_grade=ecoscore_grade,
            labels_tags__contains=labels_tags__contains,
            nova_group=nova_group,
            nutriscore_grade=nutriscore_grade,
            order_by=order_by,
            page=page,
            price_count=price_count,
            price_count__gte=price_count__gte,
            price_count__lte=price_count__lte,
            product_name__like=product_name__like,
            size=size,
            source=source,
            unique_scans_n__gte=unique_scans_n__gte,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedProductFullList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _products_list_serialize(
        self,
        brands__like,
        brands_tags__contains,
        categories_tags__contains,
        code,
        ecoscore_grade,
        labels_tags__contains,
        nova_group,
        nutriscore_grade,
        order_by,
        page,
        price_count,
        price_count__gte,
        price_count__lte,
        product_name__like,
        size,
        source,
        unique_scans_n__gte,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if brands__like is not None:
            
            _query_params.append(('brands__like', brands__like))
            
        if brands_tags__contains is not None:
            
            _query_params.append(('brands_tags__contains', brands_tags__contains))
            
        if categories_tags__contains is not None:
            
            _query_params.append(('categories_tags__contains', categories_tags__contains))
            
        if code is not None:
            
            _query_params.append(('code', code))
            
        if ecoscore_grade is not None:
            
            _query_params.append(('ecoscore_grade', ecoscore_grade))
            
        if labels_tags__contains is not None:
            
            _query_params.append(('labels_tags__contains', labels_tags__contains))
            
        if nova_group is not None:
            
            _query_params.append(('nova_group', nova_group))
            
        if nutriscore_grade is not None:
            
            _query_params.append(('nutriscore_grade', nutriscore_grade))
            
        if order_by is not None:
            
            _query_params.append(('order_by', order_by))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if price_count is not None:
            
            _query_params.append(('price_count', price_count))
            
        if price_count__gte is not None:
            
            _query_params.append(('price_count__gte', price_count__gte))
            
        if price_count__lte is not None:
            
            _query_params.append(('price_count__lte', price_count__lte))
            
        if product_name__like is not None:
            
            _query_params.append(('product_name__like', product_name__like))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        if source is not None:
            
            _query_params.append(('source', source))
            
        if unique_scans_n__gte is not None:
            
            _query_params.append(('unique_scans_n__gte', unique_scans_n__gte))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth', 
            'cookieAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/products',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def products_retrieve(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this Product.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ProductFull:
        """products_retrieve


        :param id: A unique integer value identifying this Product. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_retrieve_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProductFull",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def products_retrieve_with_http_info(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this Product.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ProductFull]:
        """products_retrieve


        :param id: A unique integer value identifying this Product. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_retrieve_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProductFull",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def products_retrieve_without_preload_content(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this Product.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """products_retrieve


        :param id: A unique integer value identifying this Product. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._products_retrieve_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProductFull",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _products_retrieve_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth', 
            'cookieAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/products/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


