# coding: utf-8

# flake8: noqa

"""
    Open Food Facts open-prices REST API

    Open Prices API allows you to add product prices

    The version of the OpenAPI document: 0.0.0 (api)
    Contact: contact@openfoodfacts.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.api_api import ApiApi
from openapi_client.api.auth_api import AuthApi
from openapi_client.api.locations_api import LocationsApi
from openapi_client.api.prices_api import PricesApi
from openapi_client.api.products_api import ProductsApi
from openapi_client.api.proofs_api import ProofsApi
from openapi_client.api.stats_api import StatsApi
from openapi_client.api.status_api import StatusApi
from openapi_client.api.users_api import UsersApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.blank_enum import BlankEnum
from openapi_client.models.currency_enum import CurrencyEnum
from openapi_client.models.location import Location
from openapi_client.models.location_create import LocationCreate
from openapi_client.models.location_osm_type_enum import LocationOsmTypeEnum
from openapi_client.models.login import Login
from openapi_client.models.null_enum import NullEnum
from openapi_client.models.paginated_location_list import PaginatedLocationList
from openapi_client.models.paginated_price_full_list import PaginatedPriceFullList
from openapi_client.models.paginated_product_full_list import PaginatedProductFullList
from openapi_client.models.paginated_proof_full_list import PaginatedProofFullList
from openapi_client.models.paginated_user_list import PaginatedUserList
from openapi_client.models.patched_price_update import PatchedPriceUpdate
from openapi_client.models.patched_price_update_currency import PatchedPriceUpdateCurrency
from openapi_client.models.patched_price_update_price_per import PatchedPriceUpdatePricePer
from openapi_client.models.patched_proof_update import PatchedProofUpdate
from openapi_client.models.price_create import PriceCreate
from openapi_client.models.price_create_location_osm_type import PriceCreateLocationOsmType
from openapi_client.models.price_full import PriceFull
from openapi_client.models.price_per_enum import PricePerEnum
from openapi_client.models.price_stats import PriceStats
from openapi_client.models.price_update import PriceUpdate
from openapi_client.models.product_full import ProductFull
from openapi_client.models.product_full_source import ProductFullSource
from openapi_client.models.proof import Proof
from openapi_client.models.proof_full import ProofFull
from openapi_client.models.proof_update import ProofUpdate
from openapi_client.models.session_full import SessionFull
from openapi_client.models.session_response import SessionResponse
from openapi_client.models.source_enum import SourceEnum
from openapi_client.models.status import Status
from openapi_client.models.total_stats import TotalStats
from openapi_client.models.type_enum import TypeEnum
from openapi_client.models.user import User
